development:
  adapter: postgresql
  database: pmnews_dev
  template: template0
  host: localhost

test:
  adapter: postgresql
  database: pmnews_dev
  template: template0
  host: localhost

production:
  adapter: postgresql
  database: pmnews_live
  template: template0
  host: pm-news.org
